export default {
    id: null,
    label: null,
    column_type: null,
    column_name: null,
    table_name: null,
    default_value: null,
    boolean: null,
    date: null,
    time: null,
    text: null,
    number: null,
    date_time: null,
    crm_mapped_field: null,
    field_type: 'standard',
    is_unique: 'no',
    visiblity: 'visible',
    is_required: false,
    listing_page: 'no',
    order_listing_page: 1,
    order_form_page: 1,
    options: [],
  }
  